### ISSUE TITLE
Only Items with Unit = Stück get copied

### ISSUE THREAD

**Issue by DST73** [heig/GrocyToBring#4]
Only item of unit "Stück" get copied to my Bring List 
![grafik](https://github.com/heig/GrocyToBring/assets/122279682/b20cdc0a-dd8c-4a1d-a7ca-3dbe21c622af)
The second item does not get copied to my Bring-List

![grafik](https://github.com/heig/GrocyToBring/assets/122279682/b683740b-31c2-4749-84f0-b02fa5d0205c)

![grafik](https://github.com/heig/GrocyToBring/assets/122279682/b697da3f-4610-4ed2-b932-a9e549e3c0f1)

Any advice please

Thank you!

**Comment by heig** [comment]
Hi, could you add something to the "src/index.php" and build and run the container again? 

In line 29 add 

`var_dump($missing_products);`

Than build and run the container, and you should get the Array of all fetched products. Could you paste this here? 
Thanks!

**Comment by DST73** [comment]
I did that as you can see in the log
[gtb.log](https://github.com/heig/GrocyToBring/files/11562533/gtb.log)

But I have noticed from looking into the code that my env-file was missing 
`SOURCE=shoppinglist`
And you all item from my grocy shopping list have been added to my Bring shopping list. (I have added before some more products to my grocy list)

![grafik](https://github.com/heig/GrocyToBring/assets/122279682/599bd1dc-9ad1-487b-8c93-b718c20010a0)

Maybe the .env-example should be updated :)

One thing would be cool if it could sync the list. I mean if you delete an item from your grocy list it gets deleted from your Bring list the next run.

Do you plan to make a self running container so there is no need for creating an cron job ?

**Comment by heig** [comment]
Well, if you do not use the Shoppinglist but only the Products that are below minimum stock, you don't need the "SOURCE" part ;) 
But of course I can add it as an empty option :) 
So I belive this issue is fixed?

**Comment by DST73** [comment]
Yes the issue is fixed... or a comment in the README :) Thank you!

**Comment by heig** [comment]
> Yes the issue is fixed... or a comment in the README :) Thank you!

[https://github.com/heig/GrocyToBring#use-shoppinglist-and-not-minimum-stock-amounts](https://github.com/heig/GrocyToBring#use-shoppinglist-and-not-minimum-stock-amounts)

done :)

**Comment by DST73** [comment]
Thank you! Would you consider my suggestion to sync the Bring shopping list? Meaning if you delete an item in the grocy list it gets delete in the bring list?
